server:
  port: 8145
  servlet:
    context-path: /api
spring:
  application:
    name: customization
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB


# 接口文档 配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.itegg.customization.controller
